#!/bin/bash
# GroupWise Admin Helpdesk Setup Launch Script API for Cimitra
# Author: Tay Kratzer tay@cimitra.com
# GitHub Location: https://github.com/cimitrasoftware/nix-api-gw

declare SOFTWARE_TITLE="Cimitra API GroupWise Module"
declare DEFAULT_INSTALL_PATH="/var/opt/cimitra/api/gw"
declare INSTALL_PATH="/var/opt/cimitra/api/gw"

echo ""
echo "Process: Installing ${SOFTWARE_TITLE}"
mkdir -p ${INSTALL_PATH} 2> /dev/null

declare -i INSTALL_PATH_EXISTS=`test -d ${INSTALL_PATH} ; echo $?`

if [ $INSTALL_PATH_EXISTS -ne 0 ]
then
echo ""
echo "Error: Cannot Access Installation Path: ${INSTALL_PATH}"
echo ""
exit 1
fi
 
cd ${INSTALL_PATH} 2> /dev/null

RESULT=`echo $?` 

if [ $RESULT -ne 0 ]
then
echo ""
echo "Error: Cannot Access Installation Path: ${INSTALL_PATH}"
echo ""
exit 1
fi

{
curl -LJO https://raw.githubusercontent.com/cimitrasoftware/nix-api-gw/master/gw
} 1> /dev/null 2>/dev/null
chmod +x ./gw

echo ""
echo "Success: Installing ${SOFTWARE_TITLE}"
echo ""
echo "Module help: cimitra gw help"
echo ""
echo "-or-"
echo ""
echo "/var/opt/cimitra/api/gw/gw"
echo ""